services:
  - type: web
    name: office-system-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
